baseURL = "https://c2pa.org/"
languageCode = "en-us"
resourceDir = "../resources"
theme = "hugo-theme-c2pa"
title = "Coalition for Content Provenance and Authenticity"

defaultContentLanguage = "en" 
paginate = 10
sectionPagesMenu = "main" 
enableRobotsTXT = false
googleAnalytics = "" 

# don't pluralize About->Abouts
pluralizelisttitles = false

[languages]
[languages.en]
contentDir = "content/en"
title = "C2PA"
weight = 1

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[params]
description = "Coalition for Content Provenance and Authenticity"
images = ['static/images/c2pa-hero.png']
favicon = "favicon.ico"
github = "https://github.com/c2pa-org"
[params.members]
steering = [
    { name = "Adobe", img = "steering/adobe.svg", href="https://www.adobe.com/" },
    { name = "BBC", img = "steering/bbc.svg", href="https://www.bbc.com/" },
    { name = "Google", img = "steering/Google-Logo.wine.svg", href="https://www.google.com" },    
    { name = "Intel", img = "steering/intel.svg", href="https://www.intel.com/" },
    { name = "Microsoft", img = "steering/microsoft.svg", href="https://www.microsoft.com/" },
    { name = "Sony", img = "steering/sony.svg", href="https://www.sony.com/" },
    { name = "Truepic", img = "steering/truepic_logo_new.png", href="https://truepic.com/" },
    { name = "Publicis Groupe", img = "steering/publicis-groupe.svg", href="https://www.publicisgroupe.com/en/splash-en" },
    { name = "OpenAI Inc", img = "steering/openai-lockup.svg", href="https://openai.com"},
]
general = [
    { name = "Arm", img = "general/arm.svg", href="https://www.arm.com/" },
    { name = "WITNESS", img = "general/witness.png", href="https://www.witness.org/" },
    { name = "RIAA", img = "general/riaa.svg", href="https://www.riaa.com/" },
    { name = "Numbers Protocol", img = "general/Numbers_Stacked_Block_Black.svg", href="https://numbersprotocol.io/" },
    { name = "Society Library", img = "general/societylibrary.svg", href="https://www.societylibrary.org/" },
    { name = "Nikon", img = "general/nikon.svg", href="https://nikon.com/" },
    { name = "Identity Technologies", img = "general/Identity_Logo.svg", href="https://www.identity.com/"},
    { name = "ATEME SA", img = "general/ateme.png", href="https://www.ateme.com/"},
    { name = "FutureWei", img = "general/futurewei_logo_rgb.png", href="https://www.futurewei.com/"},
    { name = "Digicert", img = "general/DigiCert_Blue_Logo_Large.jpeg", href="https://www.digicert.com/"},
    { name = "Canon", img = "general/canon-inc.svg", href="https://www.canon.com/"},
    { name = "Keyfactor", img = "general/logo-keyfactor_logo_charcoal.svg", href="https://www.keyfactor.com/"},
    { name = "NHK", img = "general/NHKlogo.svg", href="https://www3.nhk.or.jp/nhkworld/"},
    { name = "Amazon Web Services", img = "general/amazon-web-services-inc.svg", href="https://www.amazon.com/"},
    { name = "Cybertrust Japan", img = "general/cybertrust-logo.svg", href="https://www.cybertrust.co.jp/"},
    { name = "Leica Camera", img = "general/Leica-logo.svg", href="https://www.leica-camera.com/"},
    { name = "EADTrust", img = "general/eadtrust.svg", href="https://eadtrust.eu/en/"},
    { name = "Polygon", img = "general/polygon_logo_purple.svg" , href="https://polygon.technology"},
    { name = "ProSieben", img = "general/pro-sieben-sat-1-supporter.svg" , href="https://www.prosiebensat1.com"},
    { name = "InfoSys", img = "general/infosys_navigate_logo.svg" , href="https://www.infosys.com"},
    { name = "Qualcomm", img = "general/qualcomm-logo.png" , href="https://www.qualcomm.com"},
    { name = "Overlai LLC", img = "general/OverlaiMainLogo.svg", href="https://www.overlai.app/"},
    { name = "TikTok Inc.", img = "general/TikTok-logo-CMYK-Horizontal-Black-Simplified.svg", href="https://www.tiktok.com"},
    { name = "Fujifilm Corporation", img = "general/fujifilm_basic_il.svg", href="https://global.fujifilm.com/en/"},
    { name = "WDR", img = "general/WDR_Dachmarke.svg", href="https://www1.wdr.de/index.html"},
    { name = "Eleven Labs", img = "general/Eleven_Labs.svg", href="http://www.elevenlabs.io/"},
    { name = "Vivendi", img = "general/Vivendi.svg", href="https://www.vivendi.com/en/"},
]
contributor = [
    { name = "Accurati", img = "contributor/accuratius-logo-w-tag.svg", href="https://accurati.us/"},
    { name = "Adnkronos", img = "contributor/logo-adnkronos.svg", href="https://www.adnkronos.com"},
    { name = "Akamai", img = "contributor/akamai.png", href="https://www.akamai.com/"},
    { name = "Amazon Web Servcies", img = "contributor/amazon-web-services-inc.svg", href="https://aws.amazon.com"},
    { name = "American ChatGPT Cerification Association", img = "contributor/american-chatgpt-certification-association.svg", href="https://test-chatgpt.com"},
    { name = "Avid Technologies", img = "contributor/AVID-Logo-solid.svg", href="https://www.avid.com/"},
    { name = "Bank of America", img = "contributor/Bank-of-America-logo.svg", href="https://www.bankofamerica.com/"},
    { name = "Blockcast", img = "contributor/bc-logo-blue.svg", href="https://blockcast.net/"},
    { name = "BlockChain Commons", img = "contributor/blockchain-commons-llc.svg", href="https://www.blockchaincommons.com/home/"},
    { name = "Boclips", img = "contributor/BOCLIPS.svg", href="https://www.boclips.com/"},
    { name = "Brask", img = "contributor/brask-inc.svg", href="https://www.brask.ai"},
    { name = "Campaign Verify", img = "contributor/CV_logo_horizontal.png", href="https://www.campaignverify.org"},
    { name = "Cantina", img = "contributor/Cantina_Logo_Wordmark_stack.svg", href="https://www.cantina.com"},
    { name = "CBC", img = "contributor/cbc.svg", href="https://www.cbc.ca/" },
    { name = "CLink", img = "contributor/clink.svg", href="https://clink.media/" },
    { name = "CloakAI", img = "contributor/Cloakai-FullSizeRender-PhotoRoom.svg", href="https://cloakit.ai"},
    { name = "Comfact AB", img = "contributor/Comfact_AB.png", href=""},
    { name = "Dalet", img = "contributor/Dalet-Blue.svg", href="https://www.dalet.com/"},
    { name = "Deutsche Presse-Agentur", img = "contributor/Dpa_Logo_2021.png", href="https://dpa.com/"},
    { name = "Dhiway Networks Private Limited", img = "contributor/dhiway-networks-private-limited.svg", href=""},
    { name = "Digimarc", img = "contributor/digimarc.svg", href="https://www.digimarc.com/" },
    { name = "EZDRM", img = "contributor/ezdrm_logo_trademark.svg", href="https://ezdrm.com/"},
    { name = "Fastly", img = "contributor/fastly.svg", href="https://www.fastly.com/"},
    { name = "Fincons Group", img = "contributor/logo_fincons.svg", href="https://www.finconsgroup.com/industries/media/"},
    { name = "FRANCEtv", img = "contributor/France.tv_Logo.svg", href="https://www.francetvlab.fr/en" },
    { name = "Fraunhofer", img = "contributor/Fraunhofer.png", href="https://www.fokus.fraunhofer.de/"},
    { name = "Friends of Justin", img = "contributor/friends_of_justin-logo.png", href="https://friendsofjustin.knowbots.org"},
    { name = "Gearbrain", img = "contributor/Gearbrain_logo.jpg", href="https://www.gearbrain.com"},
    { name = "GiNi", img = "contributor/GiNi.Tech_Logo.svg", href="https://giniinc.tech"},
    { name = "GlobalSign", img = "contributor/GlobalSign.svg", href="https://www.globalsign.com/en"},
    { name = "Groulx", img = "contributor/groulxlogo.svg", href="https://groulx.ca"},
    { name = "HAND", img = "contributor/HAND_horizontal_brand_logo.jpg", href="https://handidentity.com/"},
    { name = "Imatag", img = "contributor/imatag_primary.svg", href="https://www.imatag.com/"},
    { name = "ISCC Foundation", img = "contributor/logo-black-iscc-foundation-transparent-1500.svg", href="https://iscc.codes/"},
    { name = "Itheum", img = "contributor/Itheum_Colour_Logo_and_Name.svg", href="https://www.itheum.io"},
    { name = "Jobzmall", img = "contributor/jobzmall.svg", href="https://www.jobzmall.com"},
    { name = "Journelism.design", img = "contributor/journalism.design.svg", href="https://journalism.design/"},
    { name = "Livepeer", img = "contributor/Livepeer.svg", href="https://livepeer.org"},
    { name = "Maya", img = "contributor/Maya-Logo-Blue.svg", href="https://mayalabs.tech"},
    { name = "Medex Forensics", img = "contributor/Medex_Forensics_Logo_2022.png", href="https://medexforensics.com/"},
    { name = "Melcher Systems", img = "contributor/melcher-systems.svg", href="https://melchersystem.com/"},
    { name = "Meta Martis", img = "contributor/color1_logo_transparent_background.svg", href="https://metamartis.com"},
    { name = "Metadata Authoring Systems", img = "contributor/is_logo_5sm.png", href="https://imagesnippets.com"},
    { name = "Metaphyic", img = "contributor/Metaphysic-logo-main.svg", href="https://metaphysic.ai/"},
    { name = "Metapyxl", img = "contributor/Metapyxl.png", href="https://Metapyxl.com/"},
    { name = "Monotype", img = "contributor/Monotype_Imaging_2019_logo.svg", href="https://www.monotype.com/"},
    { name = "Nodle", img = "contributor/nodle.svg", href="https://nodle.com/"},
    { name = "Noosphere Technologies", img = "contributor/noosphere-technologies-logo.svg", href="https://www.noosphere.tech"},
    { name = "Omnicom", img = "contributor/omnicom-group-inc.svg", href="https://omnicomgroup.com/"},
    { name = "Ortana Media Group", img = "contributor/ortana-media-group.svg", href="https://www.ortana.tv"},
    { name = "Panasonic", img = "contributor/Panasonic_logo_bl_posi_EPS_RGB.svg", href="https://panasonic.com/"},
    { name = "Partnership for Insurance Information", img = "contributor/PII_Logo_02.svg", href="https://insinfo.org/"},
    { name = "Partnership on AI", img = "contributor/PAI_logo.svg", href="https://partnershiponai.org/"},
    { name = "Perma.cc", img = "contributor/perma_logo.svg", href="https://www.perma.cc/"},
    { name = "PID", img = "contributor/PID-logo.png", href="https://privateid.com"},
    { name = "PixelStream", img = "contributor/pixelstream.svg", href="https://pixelstream.com/"},
    { name = "Post Platform", img = "contributor/Post_Platform_Logo.svg", href="https://postplatforms.org"},
    { name = "Quibee", img = "contributor/Quibee_verticale.svg", href="https://www.quibee.it"},
    { name = "Ravnur", img = "contributor/ravnur.svg", href="https://www.ravnur.com/"},
    { name = "Rize Labs", img = "contributor/rize-labs-bannaHQ.svg", href="https://www.bananahq.io"},
    { name = "SafeCast Limited", img = "contributor/safecast.svg", href="https://safecast.co.uk/"},
    { name = "Savage Media", img = "contributor/Savage_Media.svg", href="https://savage.app/"},
    { name = "Sedicii", img = "contributor/sedicii.svg", href="https://sedicii.com/"},
    { name = "Sequence Key", img = "contributor/sequencekey.png", href="http://sequencekey.com/"},
    { name = "Serelay", img = "contributor/serelay.png", href="https://iscc.foundation/"},
    { name = "ShutterStock", img = "contributor/sstk_standard_rgb.png", href="https://www.shutterstock.com/"},
    { name = "SmartFrame", img = "contributor/smartframe_logo.svg", href="https://smartframe.io/"},
    { name = "SPEARIT", img = "contributor/spearit.svg", href="https://www.spearit.net/"},
    { name = "Spherity", img = "contributor/Spherity-logo.svg", href="https://www.spherity.com/"},
    { name = "Steg AI", img = "contributor/stegai.png", href="https://steg.ai/"},
    { name = "StreamRoller", img = "contributor/steamroller-systems.svg", href="https://www.switchchord.com/"},
    { name = "The Daily Edit", img = "contributor/the-daily-edit.svg", href="https://dailyedit.com/"},
    { name = "The New York Times", img = "contributor/new-york-times.png", href="https://www.nytimes.com/"},
    { name = "Toothpic", img = "contributor/ToothpicLogo_no_payoff.svg", href="https://www.toothpic.eu"},
    { name = "TOPPAN", img = "contributor/toppan_logo_blue_4C.svg", href="https://www.toppan.com/en/"},
    { name = "Tractiv", img = "contributor/Tractiv_new.png", href="https://tractiv.com/"},
    { name = "Truefy", img = "contributor/Truefy_logo.svg", href="https://truefy.ai/"},
    { name = "Trufo", img = "contributor/trufo_white_on_black_w_roundcorners.svg", href="https://trufo.ai"},
    { name = "Universal Music Group", img = "contributor/UMG_LineworkLogo.png", href="https://www.universalmusic.com/"},
    { name = "Upward Solutions", img = "contributor/UPWARD.png", href="https://usi.digital/"},
    { name = "Vaulted Ventures", img = "contributor/VV_Logo_Text_Alpha_17.svg", href="https://vaulted.ventures/"},
    { name = "Verance", img = "contributor/verance.png", href="https://www.verance.com/"},
    { name = "Verifiction", img = "contributor/verifiction-logo.svg", href="https://verifiction.com"},
    { name = "Verisk Analytics", img = "contributor/veriskanalyticsinc.svg", href="https://verisk.com/"},
    { name = "Virtru", img = "contributor/Virtru_Logo_Blue.svg", href="https://www.virtru.com"},
    { name = "Weavechain", img = "contributor/Weavechain.svg", href="https://weavechain.com/"},
    { name = "Web Commodore", img = "contributor/webcommodore.png", href="https://www.webcommodore.com/"},
    { name = "Wolftech", img = "contributor/wolftech-lightbg.svg", href="https://wolftech.no"},
    { name = "Woplli Technologies", img = "contributor/wopolli_logo.svg", href="https://www.woplli.com/"},
    { name = "Wrapt Inc.", img = "contributor/wrapt_logo.svg", href="https://wrapt.com/"},
    { name = "ZRImages", img = "contributor/ZRIMAGESlogo.svg", href="https://www.zrimages.com/index"},
    { name = "Conversion Videos, Inc.", img = "contributor/convi.svg", href="https://www.convi.io/"},
    { name = "Hubbub World", img = "contributor/hubbub.svg", href="https://www.hubbubworld.com"},
    { name = "cheqd", img = "contributor/cheqd-Logo-Vertical-Orange_Black.svg", href="https://cheqd.io"},
    { name = "Authenpiq", img = "contributor/AuthenPiQLogo.svg", href="https://authenpiq.com/en/"},
    { name = "TRSCRT", img = "contributor/tsrct-logo-circle-white.svg", href="https://tsrct.io"},
    { name = "Alteon", img = "contributor/alteon.svg", href="https://alteon.io/"},
    { name = "G&L Digital Media Engineering", img = "contributor/gl-logo.svg", href="https://www.gl-systemhaus.de/en/"},
    { name = "Liccium", img = "contributor/Licciumhorizontal.svg", href="https://liccium.com"},
    { name = "QueryVision", img = "contributor/queryvision.png", href="http://queryvision.com"},
    { name = "Animechain", img = "contributor/animechain.svg", href="https://animechain.ai"},
    { name = "Warner Brothers Discovery", img = "contributor/WBD.png", href="https://wbd.com"},
    { name = "The Creative", img = "contributor/creativeArtboard1.svg", href="https://creativeplatform.xyz/"},
    { name = "Certificall", img = "contributor/Certificall_logo_noir_rvb.svg", href="https://certificall.app/"},
    { name = "Electronic Arts", img = "contributor/EA_Medallion_Black_CMYK.svg", href="https://www.ea.com/"},
    { name = "Scenes", img = "contributor/scenes.svg", href="https://scenes.dk/"},
    { name = "Digital Governance Institute", img = "contributor/DGILetterheadWhite.svg", href="https://digitalgovernanceinstitute.com/"},
    { name = "Witness", img = "contributor/witness-lockup-horizontal-black.svg", href="https://witness.co"},
    { name = "Aptos Labs", img = "contributor/aptoslabslogohorizontal.svg", href="https://aptoslabs.com"},
    { name = "Mosaic Inc", img = "contributor/mosaic_c2pa_logomark.svg", href="https://try.onmosaic.com"},
    { name = "Metabroadcast", img = "contributor/MetaBroadcast_Horizontal_Fullcolour_rgb.svg", href="https://metabroadcast.com/"},
    { name = "CNA", img = "contributor/CNAlogo.svg", href="https://www.channelnewsasia.com/international"},
    { name = "Imagist", img = "contributor/imagist.svg", href="https://imagist.app"},
    { name = "Nablas", img = "contributor/nablas_logo_horizontal-svg.svg", href="https://www.nablas.com/"},
    { name = "Naver Inc", img = "contributor/Logotype_Green.svg", href="https://navercorp.com"},
    { name = "Glisco Internet Services", img = "contributor/glisco-internet-services.svg", href="https://glisco.de"},
    { name = "HeyGen", img = "contributor/heygen_logo_v.svg", href="https://www.heygen.com"},
    { name = "Zoloz Inc. ", img = "contributor/Zoloz.svg", href="zoloz.com"},
    { name = "Audio Futures", img = "contributor/AudioFuturesLogo.svg", href="https://360ra.com"},
    { name = "NCC Group", img = "contributor/NCCLogo.svg", href="https://www.nccgroup.com/"},
    { name = "Welcome to the Arkage", img = "contributor/Arkage.svg", href="https://welcometothearkage.com"},
    { name = "Eluvio Inc", img = "contributor/Eluvio.svg", href="https://eluv.io"},
    { name = "TrustNXT", img = "contributor/TrustNXT.svg", href="https://trustnxt.com/"},
    { name = "Dai Nippon Printing Co., Ltd.", img = "contributor/DaiNippon.svg", href="https://www.global.dnp"},
    { name = "Financial Times", img = "contributor/FT.svg", href="https://www.ft.com"},
    { name = "Data Transfer Initiative", img = "contributor/DataTransfer.svg", href="https://dtinit.org"},
    { name = "Polygraph, Inc", img = "contributor/PolygrafLogo.svg", href="https://polygraf.ai/"},
    { name = "b<>com", img = "contributor/bcom.svg", href="https://b-com.com/"},
    { name = "Durer AI", img = "contributor/durer.svg", href="https://exactly.ai"},
]

[menu]
[[menu.main]]
identifier = "about"
title = "About"
url = "/about/"
weight = 5
[[menu.main]]
identifier = "faq"
title = "FAQ"
url = "/faq/"
weight = 10
[[menu.main]]
identifier = "principles"
title = "Guiding Principles"
url = "/principles/"
weight = 20
[[menu.main]]
identifier = "spec"
title = "Specification"
url = "https://c2pa.org/specifications/specifications/2.0/index.html"
weight = 25
[[menu.main]]
identifier = "membership"
title = "Membership"
url = "/membership/"
weight = 30
[[menu.main]]
identifier = "post"
title = "News"
url = "/post/"
weight = 40
[[menu.main]]
identifier = "contact"
title = "Contact"
url = "/contact/"
weight = 50
[[menu.main]]
identifier = "_github"
title = "GitHub"
weight = 60

[build]
writeStats = true

[markup.goldmark.renderer]
  unsafe = true
