baseURL = "https://c2pa.org/"
languageCode = "en-us"
resourceDir = "../resources"
theme = "hugo-theme-c2pa"
title = "Coalition for Content Provenance and Authenticity"

defaultContentLanguage = "en" 
paginate = 10
sectionPagesMenu = "main" 
enableRobotsTXT = false
googleAnalytics = "" 

# don't pluralize About->Abouts
pluralizelisttitles = false

[languages]
[languages.en]
contentDir = "content/en"
title = "C2PA"
weight = 1

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[params]
description = "Coalition for Content Provenance and Authenticity"
images = ['static/images/c2pa-hero.png']
favicon = "favicon.ico"
github = "https://github.com/c2pa-org"
[params.members]
steering = [
    { name = "Adobe", img = "steering/adobe.svg", href="https://www.adobe.com/" },
    { name = "BBC", img = "steering/bbc.svg", href="https://www.bbc.com/" },
    { name = "Google", img = "steering/Google-Logo.wine.svg", href="https://www.google.com" },    { name = "Intel", img = "steering/intel.svg", href="https://www.intel.com/" },
    { name = "Microsoft", img = "steering/microsoft.svg", href="https://www.microsoft.com/" },
    { name = "Sony", img = "steering/sony.svg", href="https://www.sony.com/" },
    { name = "Truepic", img = "steering/truepic_logo_new.png", href="https://truepic.com/" },
    { name = "Publicis Groupe", img = "steering/publicis-groupe.svg", href="https://www.publicisgroupe.com/en/splash-en" },
]
general = [
    { name = "Arm", img = "general/arm.svg", href="https://www.arm.com/" },
    { name = "WITNESS", img = "general/witness.png", href="https://www.witness.org/" },
    { name = "RIAA", img = "general/riaa.svg", href="https://www.riaa.com/" },
    { name = "Numbers Protocol", img = "general/Numbers_Stacked_Block_Black.svg", href="https://numbersprotocol.io/" },
    { name = "Society Library", img = "general/societylibrary.svg", href="https://www.societylibrary.org/" },
    { name = "Nikon", img = "general/nikon.svg", href="https://nikon.com/" },
    { name = "Identity Technologies", img = "general/Identity_Logo.svg", href="https://www.identity.com/"},
    { name = "ATEME SA", img = "general/ateme.png", href="https://www.ateme.com/"},
    { name = "FutureWei", img = "general/futurewei_logo_rgb.png", href="https://www.futurewei.com/"},
    { name = "Digicert", img = "general/DigiCert_Blue_Logo_Large.jpeg", href="https://www.digicert.com/"},
    { name = "Canon", img = "general/canon-inc.svg", href="https://www.canon.com/"},
    { name = "Keyfactor", img = "general/logo-keyfactor_logo_charcoal.svg", href="https://www.keyfactor.com/"},
    { name = "NHK", img = "general/NHKlogo.svg", href="https://www3.nhk.or.jp/nhkworld/"},
    { name = "Amazon Web Services", img = "general/amazon-web-services-inc.svg", href="https://www.amazon.com/"},
    { name = "Cybertrust Japan", img = "general/cybertrust-logo.svg", href="https://www.cybertrust.co.jp/"},
    { name = "Leica Camera", img = "general/Leica-logo.svg", href="https://www.leica-camera.com/"},
    { name = "Alteon", img = "general/alteon.svg", href="https://alteon.io/"},
    { name = "EADTrust", img = "general/eadtrust.svg", href="https://eadtrust.eu/en/"},
]
contributor = [
    { name = "Blockcast", img = "contributor/bc-logo-blue.svg", href="https://blockcast.net/"},
    { name = "CBC", img = "contributor/cbc.svg", href="https://www.cbc.ca/" },
    { name = "CLink", img = "contributor/clink.svg", href="https://clink.media/" },
    { name = "Digimarc", img = "contributor/digimarc.svg", href="https://www.digimarc.com/" },
    { name = "FRANCEtv", img = "contributor/France.tv_Logo.svg", href="https://www.francetvlab.fr/en" },
    { name = "Dalet", img = "contributor/Dalet-Blue.svg", href="https://www.dalet.com/"},
    { name = "Serum of Truth", img = "contributor/serumoftruth.JPG", href="https://serumoftruth.com/"},
    { name = "Ravnur", img = "contributor/ravnur.svg", href="https://www.ravnur.com/"},
    { name = "Web Commodore", img = "contributor/webcommodore.png", href="https://www.webcommodore.com/"},
    { name = "Akamai", img = "contributor/akamai.png", href="https://www.akamai.com/"},
    { name = "Melcher Systems", img = "contributor/melcher-systems.svg", href="https://melchersystem.com/"},
    { name = "The New York Times", img = "contributor/new-york-times.png", href="https://www.nytimes.com/"},
    { name = "Steg AI", img = "contributor/stegai.png", href="https://steg.ai/"},
    { name = "Fastly", img = "contributor/fastly.svg", href="https://www.fastly.com/"},
    { name = "SafeCast Limited", img = "contributor/safecast.svg", href="https://safecast.co.uk/"},
    { name = "Metadata Authoring Systems", img = "contributor/is_logo_5sm.png", href="https://imagesnippets.com"},
    { name = "Serelay", img = "contributor/serelay.png", href="https://iscc.foundation/"},
    { name = "Sedicii", img = "contributor/sedicii.svg", href="https://sedicii.com/"},
    { name = "Sequence Key", img = "contributor/sequencekey.png", href="http://sequencekey.com/"},
    { name = "Woplli Technologies", img = "contributor/wopolli_logo.svg", href="https://www.woplli.com/"},
    { name = "SmartFrame", img = "contributor/smartframe_logo.svg", href="https://smartframe.io/"},
    { name = "Truefy", img = "contributor/Truefy_logo.svg", href="https://truefy.ai/"},
    { name = "Partnership on AI", img = "contributor/PAI_logo.svg", href="https://partnershiponai.org/"},
    { name = "Comfact AB", img = "contributor/Comfact_AB.png", href=""},
    { name = "Deutsche Presse-Agentur", img = "contributor/Dpa_Logo_2021.png", href="https://dpa.com/"},
    { name = "Medex Forensics", img = "contributor/Medex_Forensics_Logo_2022.png", href="https://medexforensics.com/"},
    { name = "Metapyxl", img = "contributor/Metapyxl.png", href="https://Metapyxl.com/"},
    { name = "Bank of America", img = "contributor/Bank-of-America-logo.svg", href="https://www.bankofamerica.com/"},
    { name = "Journelism.design", img = "contributor/journalism.design.svg", href="https://journalism.design/"},
    { name = "The Daily Edit", img = "contributor/the-daily-edit.svg", href="https://dailyedit.com/"},
    { name = "Verisk Analytics", img = "contributor/veriskanalyticsinc.svg", href="https://verisk.com/"},
    { name = "EZDRM", img = "contributor/ezdrm_logo_trademark.svg", href="https://ezdrm.com/"},
    { name = "ISCC Foundation", img = "contributor/logo-black-iscc-foundation-transparent-1500.svg", href="https://iscc.codes/"},
    { name = "Wrapt Inc.", img = "contributor/wrapt_logo.svg", href="https://wrapt.com/"},
    { name = "Panasonic", img = "contributor/Panasonic_logo_bl_posi_EPS_RGB.svg", href="https://panasonic.com/"},
    { name = "Tractiv", img = "contributor/Tractiv_new.png", href="https://tractiv.com/"},
    { name = "PixelStream", img = "contributor/pixelstream.svg", href="https://pixelstream.com/"},
    { name = "HAND", img = "contributor/HAND_horizontal_brand_logo.jpg", href="https://handidentity.com/"},
    { name = "TOPPAN", img = "contributor/toppan_logo_blue_4C.svg", href="https://www.toppan.com/en/"},
    { name = "Metaphyic", img = "contributor/Metaphysic-logo-main.svg", href="https://metaphysic.ai/"},
    { name = "StreamRoller", img = "contributor/steamroller-systems.svg", href="https://www.switchchord.com/"},
    { name = "Universal Music Group", img = "contributor/UMG_LineworkLogo.png", href="https://www.universalmusic.com/"},
    { name = "Monotype", img = "contributor/Monotype_Imaging_2019_logo.svg", href="https://www.monotype.com/"},
    { name = "ShutterStock", img = "contributor/sstk_standard_rgb.png", href="https://www.shutterstock.com/"},
    { name = "Upward Solutions", img = "contributor/UPWARD.png", href="https://usi.digital/"},
    { name = "Friends of Justin", img = "contributor/friends_of_justin-logo.png", href="https://friendsofjustin.knowbots.org"},
    { name = "Avid Technologies", img = "contributor/AVID-Logo-solid.svg", href="https://www.avid.com/"},
    { name = "Vaulted Ventures", img = "contributor/VV_Logo_Text_Alpha_17.svg", href="https://vaulted.ventures/"},
    { name = "SPEARIT", img = "contributor/spearit.svg", href="https://www.spearit.net/"},
    { name = "Spherity", img = "contributor/Spherity-logo.svg", href="https://www.spherity.com/"},
    { name = "Verance", img = "contributor/verance.png", href="https://www.verance.com/"},
    { name = "Imatag", img = "contributor/imatag_primary.svg", href="https://www.imatag.com/"},
    { name = "Perma.cc", img = "contributor/perma_logo.svg", href="https://www.perma.cc/"},
    { name = "Boclips", img = "contributor/BOCLIPS.svg", href="https://www.boclips.com/"},
    { name = "American ChatGPT Certification Association", img = "contributor/american-chatgpt-certification-association.svg", href=""},
    { name = "Rize Labs", img = "contributor/rize-labs-bannaHQ.svg", href=""},
    { name = "Dhiway Networks Private Limited", img = "contributor/dhiway-networks-private-limited.svg", href=""},
    { name = "Overlai", img = "contributor/overlai-llc.svg", href=""},
    { name = "Nodle", img = "contributor/nodle.svg", href=""},
    { name = "Cloakit.ai", img = "contributor/cloakai_logo_v3.svg", href=""},
]

[menu]
[[menu.main]]
identifier = "about"
title = "About"
url = "/about/"
weight = 5
[[menu.main]]
identifier = "faq"
title = "FAQ"
url = "/faq/"
weight = 10
[[menu.main]]
identifier = "principles"
title = "Guiding Principles"
url = "/principles/"
weight = 20
[[menu.main]]
identifier = "spec"
title = "Specification"
url = "https://c2pa.org/specifications/specifications/2.0/index.html"
weight = 25
[[menu.main]]
identifier = "membership"
title = "Membership"
url = "/membership/"
weight = 30
[[menu.main]]
identifier = "post"
title = "News"
url = "/post/"
weight = 40
[[menu.main]]
identifier = "contact"
title = "Contact"
url = "/contact/"
weight = 50
[[menu.main]]
identifier = "_github"
title = "GitHub"
weight = 60

[build]
writeStats = true

[markup.goldmark.renderer]
  unsafe = true
