baseURL = "https://c2pa.org/"
languageCode = "en-us"
resourceDir = "../resources"
theme = "hugo-theme-c2pa"
title = "Coalition for Content Provenance and Authenticity"

defaultContentLanguage = "en" 
paginate = 10
sectionPagesMenu = "main" 
enableRobotsTXT = false
googleAnalytics = "" 

# don't pluralize About->Abouts
pluralizelisttitles = false

[languages]
[languages.en]
contentDir = "content/en"
title = "C2PA"
weight = 1

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[params]
description = "Coalition for Content Provenance and Authenticity"
favicon = "favicon.ico"
github = "https://github.com/c2pa-org"
[params.members]
steering = [
    { name="Adobe", img = "steering/adobe.svg", href="https://www.adobe.com/" },
    { name="Arm", img = "steering/arm.svg", href="https://www.arm.com/" },
    { name="BBC", img = "steering/bbc.svg", href="https://www.bbc.com/" },
    { name="Intel", img = "steering/intel.svg", href="https://www.intel.com/" },
    { name="Microsoft", img = "steering/microsoft.svg", href="https://www.microsoft.com/" },
    { name="Truepic", img = "steering/truepic.svg", href="https://truepic.com/" },
    { name="Twitter", img = "steering/twitter.svg", href="https://twitter.com/" },
]
general = [
    { name = "WITNESS", img = "general/witness.svg", href="https://www.witness.org/" },
    { name = "RIAA", img = "general/riaa.svg", href="https://www.riaa.com/" },
    { name = "FRANCEtv", img = "general/France.tv_Logo.svg", href="https://www.francetvlab.fr/en" },
    { name = "Numbers Protocol", img = "general/numbers-logo-square.svg", href="https://numbersprotocol.io/" },
]
contributor = [
    { name = "CBC", img = "contributor/cbc.svg", href="https://www.cbc.ca/" },
    { name = "CLink", img = "contributor/clink.svg", href="https://clink.media/" },
    { name = "Digimarc", img = "contributor/digimarc.svg", href="https://www.digimarc.com/" },
    { name = "Dalet", img = "contributor/Dalet-Blue.svg", href="https://www.dalet.com/"},
    { name = "Serum of Truth", img = "contributor/serumoftruth.JPG", href="https://serumoftruth.com/"},
    { name = "Ravnur", img = "contributor/ravnur.svg", href="https://www.ravnur.com/"},
    { name = "Web Commodore", img = "contributor/webcommodore.png", href="https://www.webcommodore.com/"},
    { name = "Akamai", img = "contributor/akamai.png", href="https://www.akamai.com/"},
    { name = "Melcher Systems", img = "contributor/melcher-systems.svg", href="https://melchersystem.com/"},
    { name = "The New York Times", img = "contributor/new-york-times.png", href="hhttps://www.nytimes.com/"},
    { name = "Steg AI", img = "contributor/stegai.png", href="https://steg.ai/"},
    { name = "Fastly", img = "contributor/fastly.svg", href="http://fastify.com//"},

]

[menu]
[[menu.main]]
identifier = "about"
title = "About"
url = "/about/"
weight = 5
[[menu.main]]
identifier = "faq"
title = "FAQ"
url = "/faq/"
weight = 10
[[menu.main]]
identifier = "principles"
title = "Guiding Principles"
url = "/principles/"
weight = 20
[[menu.main]]
identifier = "membership"
title = "Membership"
url = "/membership/"
weight = 30
[[menu.main]]
identifier = "post"
title = "News"
url = "/post/"
weight = 40
[[menu.main]]
identifier = "contact"
title = "Contact"
url = "/contact/"
weight = 50
[[menu.main]]
identifier = "_github"
title = "GitHub"
weight = 60

[build]
writeStats = true
